User.create(nickname:'aaa111', email:'aaa111@aaa111', password:'aaa111', family_name:'サンプル', first_name:'太郎', birth_date:'1920-01-01')
User.create(nickname:'abc123', email:'abc123@abc123', password:'abc123', family_name:'サンプル', first_name:'次郎', birth_date:'1920-01-01')
User.create(nickname:'上原浩治', email:'uehara19@uehara19', password:'uehara19', family_name:'上原', first_name:'浩治', birth_date:'1920-04-01')
User.create(nickname:'松坂大輔', email:'matsu18@matsu18', password:'matsu18', family_name:'松坂', first_name:'大輔', birth_date:'1920-01-01')
product = Product.find(1)
Product.create!(name:'アーモンド', price:2000, quantity:"2kg", explanation:"国産", category_id:2, condition_id:2, prefecture_id:22, shipment_term_id:2, shipment_fee_id:3, user_id:2, image: product.image.attach(io: File.open('./db/fixtures/img1.jpg'), filename: 'img1.jpg'))
# Product.create!(name:'アンチョビ', price:2000, quantity:"20缶", explanation:"イタリア産", category_id:2, condition_id:2, prefecture_id:22, shipment_term_id:2, shipment_fee_id:2, user_id:1, image: File.open("app/assets/images/note-pen.jpg"))
# product = Product.find(1)
# product.image.attach(io: File.open('./db/fixtures/img1.jpg'), filename: 'img1.jpg')